### ISSUE TITLE
updating form v1.0.4 to v1.0.5 failing vulnerability check

### ISSUE THREAD

**Issue by vasanth-kumar-m-y** [Lucas-C/pre-commit-hooks-bandit#11]
updating form `v1.0.4 to v1.0.5` failing with this error, was working good with `v1.0.4`

```
- hook id: python-bandit-vulnerability-check
- exit code: 2

[main]	ERROR	No targets found in CLI or ini files, exiting.
```

here is my configuration
```
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check
        args: ["--verbose"]
        files: "lambdas"
```

**Comment by Lucas-C** [comment]
Is the repo you are using it public? If so, could please share it?

**Comment by vasanth-kumar-m-y** [comment]
> Is the repo you are using it public? If so, could please share it?

No, Lucas-C its a prviate repo

**Comment by Lucas-C** [comment]
Could specify the content of your `setup.py` or `requirements.txt` then?

Otherwise, it will be difficult to reproduce your issue...

**Comment by vasanth-kumar-m-y** [comment]
yes sure.. contents of `tox.ini`

```
[testenv:pytest]
deps =
    mock
    pytest-mock
    requests-mock
    coverage
    bandit
whitelist_externals =
    sed
    bash
    tee
commands =
    bandit --format json --output bandit-report.json --recursive lambdas
```

**Comment by Lucas-C** [comment]
This is strange... Not much has changed between those 2 releases:
https://github.com/Lucas-C/pre-commit-hooks-bandit/compare/v1.0.4...v1.0.5

What is bandit behaviour using the latest version?

Sorry, I do not really see how this `pre-commit` behaviour could have changed regarding `tox.ini` files...
I only ever used it with `requirements.txt` / `setup.py` files.

If you find more information / dig deeper into this, please share your findings!

**Comment by vasanth-kumar-m-y** [comment]
using latest version of `bandit==1.7.0` 

`pre-commit autoupdate` command updated pre-commit-hooks-bandit  `v1.0.4 to v1.0.5` and the bandit command `bandit --format json --output bandit-report.json --recursive lambdas` failing with the above error.

May be need to provide positional arguments `targets` as the error says `[main] ERROR No targets found in CLI or ini files, exiting` not sure, using latest version of bandit only chnage is pre-commit-hooks-bandit `v1.0.4 to v1.0.5`

**Comment by Lucas-C** [comment]
What is your `bandit --version` and `pre-commit --version` please?

Could you share your `.pre-commit-config.yaml`?

And finally, could you please provide the output of the command?
```
head ~/.cache/pre-commit/*/py_env-python3/lib/python*/site-packages/bandit-*.dist-info/METADATA
```

**Comment by vasanth-kumar-m-y** [comment]
`bandit --version 1.7.0,  pre-commit --version 2.13.0`

```
.pre-commit-config.yaml

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check
        args: ["--verbose"]
        files: "lambdas"
```
`head ~/.cache/pre-commit/*/py_env-python3/lib/python*/site-packages/bandit-*.dist-info/METADATA` No such file or directory
