### ISSUE TITLE
Checks all files instead of changed ones

### ISSUE THREAD

**Issue by Dunedan** [Lucas-C/pre-commit-hooks-bandit#2]
If `args` in the hook config isn't present the check checks all files instead of the ones queued for commit. That leads to very long run times for large projects.

Scans all files:
```yaml
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.2
    hooks:
    -   id: python-bandit-vulnerability-check
```

Works as expected:
```yaml
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.2
    hooks:
    -   id: python-bandit-vulnerability-check
        args: []
```
